blank_issues_enabled: false
contact_links:
  - name: GitHub discussion tab
    url: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions
    about: Please ask and answer questions here